# Generated by Django 3.0.6 on 2020-05-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_tittle', models.CharField(max_length=100)),
                ('project_link', models.URLField()),
                ('technologies', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
                ('date_finished', models.DateField()),
                ('image', models.ImageField(upload_to='media/projects/% Y/% m/% d/')),
            ],
        ),
    ]
