# Generated by Django 3.0.6 on 2020-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
                ('date_finished', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
