# Generated by Django 3.0.6 on 2020-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200508_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='project_link',
            field=models.URLField(blank=True),
        ),
    ]
