# Generated by Django 3.0.6 on 2020-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='project_link',
            field=models.URLField(),
        ),
    ]
