# Generated by Django 3.0.6 on 2020-05-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200508_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='project_name',
            new_name='blog_name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='project_link',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='technologies',
        ),
    ]
